[package]
name = "rnet"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.126"
rand = { version = "0.8.5", optional = true }

[profile.release]
lto = true
strip = true

[lib]
name = "rnet_native"
crate-type = ["cdylib"]

[features]
default = ["rand"]
rand = ["dep:rand"]
